---
- stat:
    path: /usr/bin/docker
  register: st

- name: Checked docker, Install if not install
  include_tasks: install_docker.yml
  when: st.stat.exists == False
  
- stat:
    path: /usr/local/bin/docker-compose
  register: stcomp

- name: hecked docker_compose, Install if not install
  include_tasks: install_docker_compose.yml
  when: stcomp.stat.exists == False

- name: Deploy-application
  include_tasks: deploy_docker_service.yml

- name: Undeploy-application
  include_tasks: undeploy_docker_service.yml
  tags: 
    - never 
    - undeploy